stages:
- build

variables:
  Configuration: Release
  NoSourceLink: 'true'
  
master build:
  stage: build
  image: microsoft/dotnet:2.1-sdk
  script:
  - ./build.sh
  - dotnet publish -r linux-x64 -o $PWD/artifacts/consul-rx-template/linux-x64 Templating.CommandLine/ConsulRx.Templating.CommandLine.csproj
  - mkdir artifacts/packages
  - 'cp */bin/Release/*.nupkg ./artifacts/packages'
  artifacts:
    name: 'consul-rx-$CI_PIPELINE_ID'
    when: on_success
    paths: 
    - artifacts
  only:
  - master
  
ci build:
  stage: build
  image: microsoft/dotnet:2.1-sdk
  script:
  - ./build.sh
  except:
  - tags
  - master